#!/bin/tcsh -f
#
# MCGET YYYY MO DD, e.g.
# MCGET 2016 06 25, or
# MCGET 2016 6 25, etc
#
# Downloads a bunch of data from the MC-PH1_0248
#
# After this, run in Matlab, e.g.
# mcms2mat(2016,06,25,21)
#
# Last modified by fjsimons-at-alum.mit.edu, 06/27/2016

# Where is the instrument reachable
set IP = 169.254.47.47

# Set this flag if you need to
set flag  = "-o PubkeyAuthentication=no"

# Parameters of the "search"
set yr = $1
set mo = `printf "%2.2i" $2`
set dy = `printf "%2.2i" $3`

# Where you will put it
set mydata = $MC
set myddir = $mydata/$yr/$mo/$dy 

# If you didn't have it, will make it
test ! -d $mydata && mkdir $mydata
test ! -d $mydata/$yr && mkdir $mydata/$yr
test ! -d $mydata/$yr/$mo && mkdir $mydata/$yr/$mo
test ! -d $myddir && mkdir $myddir

# This is where it thinks it is

echo Downloading /media/removable0/$yr/$mo/$dy/\* to $myddir

scp $flag $USER@$IP\:/media/removable0/$yr/$mo/$dy/\* $myddir

