#!/bin/tcsh -f
#
# Converts a miniseed file (obtained from MCGETMS) to a properly named
# SAC file via the intermediary of MSEED2SAC, [historically: still moved
# mv .S0001..HHX.D.2017.073.170000.SAC PP.S0001.00.HHX.D.2017.073.170000.SAC]
# Currently, the KNETWK and KHOLE have already been set, going forward.
#
# Only exception where this needed to be done by hand is 2017/06/19
# when the conversion between old and new file name convention
# happened right at the 18th hour. 
#
# [Historical note: if MSEED2SAC returns more than one file, dated at
# past the ??000 hour, these were due to small timing errors, and we
# got rid of those, while keeping a log. GPS fixed 06/20/2017.]
#
# Last modified by jirving-at-princeton.edu on 03/30/2018
# Last modified by fjsimons-at-alum.mit.edu on 02/21/2020

# See also IFEMPTYREMOVE

# Fix permissions, if you'd done any before, will refuse to redo it

# OLD FILES, which didn't have this set yet, new files do
set KNETWK = PP
set KHOLE  = 00

# Into the directory structure
set years = `ls -d 20??`
# SPECIFIC YEAR ########################################
set years = 2018

# Go in, come out!
foreach year ($years[*])
    cd $year
    set monts = `ls -d ??`
    # SPECIFIC MONTH ########################################
    set monts = 05

    foreach mont ($monts[*])
	cd $mont
	set days = `ls -d ??`
	# SPECIFIC DAY ########################################
	set days = 27
	
	foreach day ($days[*])
            cd $day
	    # OLD FILES ########################################
	    set files = `ls S0001.*.miniseed`
	    # NEW FILES ########################################
	    set files = `ls PP.S0001.*.miniseed`

	    foreach file ($files[*])
	       # CONVERSION
               mseed2sac $file
	       # We think there should only be one file created, with the same time as in the filename
	       # which, in practice, should be a very round number, e.g. 120000
	       set exptim = `echo $file | sed 's/\_/ /g' | sed 's/\.miniseed//g' | awk '{print $NF}'`
	       # And so we rename this file, assuming it exists

               # OLD BEHAVIOR ########################################
	       # set oldfile = `ls .S0001..*{$exptim}.SAC`
               # set newfile = `echo $oldfile | sed 's/\.\./\.'$KHOLE'\./g'`
               # mv $oldfile {$KNETWK}$newfile
	       # Keep a record of the files that showed up unexpectedly, and were not converted
	       # Ignore the "no match" statements, that means there wasn't anything unexpected
               # ls .S0001..*.SAC >>! notconverted
	       # And remove them, ignoring the "no match" statements
               # /bin/rm .S0001..*.SAC

               # NEW BEHAVIOR ########################################
	       # We get most of it right, except it may not have a bunch of zeros where we want it
	       set exphrs = `echo $exptim | sed 's/0000//g'`
	       set badfile = `ls PP.S0001.*{$exphrs}[1-9]???.SAC` 
               /bin/rm -f $badfile
               echo $badfile >>! notconverted
            end
            cd ..
        end
	cd ..
    end
    cd ..
end

# For the OLD FILES
# Then do a bunch of setvar.pl for KINSTM, see SAC2SAC
